/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateDeploymentParams {
  'name' : string,
  'architecture' : string,
  'githubUrl' : string,
  'deployedUrl' : string,
  'engineType' : string,
}
export interface CreateIdeaParams {
  'status' : string,
  'ideaType' : string,
  'name' : string,
  'googleUrl' : string,
  'instaUrl' : string,
  'description' : string,
  'photoUrl' : [] | [string],
  'deadline' : string,
  'place' : string,
  'youtubeUrl' : string,
  'problem' : string,
}
export interface CreateIncubatorParams {
  'name' : string,
  'pptFileName' : [] | [string],
  'srcFileName' : [] | [string],
  'googleUrl' : string,
  'instaUrl' : string,
  'imageUrl' : [] | [string],
  'docFileName' : [] | [string],
  'youtubeUrl' : string,
}
export interface CreateTaskParams {
  'description' : string,
  'taskDate' : string,
  'taskTime' : string,
}
export interface DashboardStats {
  'pendingIdeas' : bigint,
  'liveProjects' : bigint,
  'completedProjects' : bigint,
}
export interface Deployment {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'architecture' : string,
  'githubUrl' : string,
  'deployedUrl' : string,
  'callerId' : UserId,
  'engineType' : string,
}
export interface DownloadFileResult {
  'contentType' : string,
  'data' : Uint8Array,
  'filename' : string,
}
export interface Idea {
  'id' : bigint,
  'status' : string,
  'ideaType' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'googleUrl' : string,
  'instaUrl' : string,
  'description' : string,
  'photoUrl' : [] | [string],
  'deadline' : string,
  'callerId' : UserId,
  'place' : string,
  'youtubeUrl' : string,
  'problem' : string,
}
export interface IncubatorProject {
  'id' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'pptFileName' : [] | [string],
  'srcFileName' : [] | [string],
  'googleUrl' : string,
  'instaUrl' : string,
  'callerId' : UserId,
  'imageUrl' : [] | [string],
  'docFileName' : [] | [string],
  'youtubeUrl' : string,
}
export type ObjectId = string;
export interface Task {
  'id' : bigint,
  'createdAt' : Timestamp,
  'description' : string,
  'taskDate' : string,
  'taskTime' : string,
  'callerId' : UserId,
}
export type Timestamp = bigint;
export interface UpdateDeploymentParams {
  'name' : string,
  'architecture' : string,
  'githubUrl' : string,
  'deployedUrl' : string,
  'engineType' : string,
}
export interface UpdateIdeaParams {
  'status' : string,
  'ideaType' : string,
  'name' : string,
  'googleUrl' : string,
  'instaUrl' : string,
  'description' : string,
  'photoUrl' : [] | [string],
  'deadline' : string,
  'place' : string,
  'youtubeUrl' : string,
  'problem' : string,
}
export interface UpdateIncubatorParams {
  'name' : string,
  'pptFileName' : [] | [string],
  'srcFileName' : [] | [string],
  'googleUrl' : string,
  'instaUrl' : string,
  'imageUrl' : [] | [string],
  'docFileName' : [] | [string],
  'youtubeUrl' : string,
}
export interface UpdateTaskParams {
  'description' : string,
  'taskDate' : string,
  'taskTime' : string,
}
export interface UploadFileResult {
  'contentType' : string,
  'size' : bigint,
  'filename' : string,
  'objectId' : ObjectId,
}
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'displayName' : string,
  'email' : string,
  'profilePhotoUrl' : [] | [string],
}
export interface WebLink {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'callerId' : UserId,
}
export interface _SERVICE {
  'addWebLink' : ActorMethod<[string, string], WebLink>,
  'createDeployment' : ActorMethod<[CreateDeploymentParams], Deployment>,
  'createIdea' : ActorMethod<[CreateIdeaParams], Idea>,
  'createIncubatorProject' : ActorMethod<
    [CreateIncubatorParams],
    IncubatorProject
  >,
  'createTask' : ActorMethod<[CreateTaskParams], Task>,
  'deleteDeployment' : ActorMethod<[bigint], boolean>,
  'deleteFile' : ActorMethod<[ObjectId], boolean>,
  'deleteIdea' : ActorMethod<[bigint], boolean>,
  'deleteIncubatorProject' : ActorMethod<[bigint], boolean>,
  'deleteTask' : ActorMethod<[bigint], boolean>,
  'deleteWebLink' : ActorMethod<[bigint], boolean>,
  'downloadFile' : ActorMethod<[ObjectId], [] | [DownloadFileResult]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDeployments' : ActorMethod<[], Array<Deployment>>,
  'getIdeas' : ActorMethod<[], Array<Idea>>,
  'getIncubatorProjects' : ActorMethod<[], Array<IncubatorProject>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getWebLinks' : ActorMethod<[], Array<WebLink>>,
  'saveUserProfile' : ActorMethod<[string, string, [] | [string]], UserProfile>,
  'updateDeployment' : ActorMethod<
    [bigint, UpdateDeploymentParams],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateIdea' : ActorMethod<
    [bigint, UpdateIdeaParams],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateIncubatorProject' : ActorMethod<
    [bigint, UpdateIncubatorParams],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateTask' : ActorMethod<
    [bigint, UpdateTaskParams],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadIdeaPhoto' : ActorMethod<
    [string, string, Uint8Array],
    { 'ok' : UploadFileResult } |
      { 'err' : string }
  >,
  'uploadIncubatorDoc' : ActorMethod<
    [string, string, Uint8Array],
    { 'ok' : UploadFileResult } |
      { 'err' : string }
  >,
  'uploadIncubatorImage' : ActorMethod<
    [string, string, Uint8Array],
    { 'ok' : UploadFileResult } |
      { 'err' : string }
  >,
  'uploadIncubatorPpt' : ActorMethod<
    [string, string, Uint8Array],
    { 'ok' : UploadFileResult } |
      { 'err' : string }
  >,
  'uploadIncubatorSrc' : ActorMethod<
    [string, string, Uint8Array],
    { 'ok' : UploadFileResult } |
      { 'err' : string }
  >,
  'uploadProfilePhoto' : ActorMethod<
    [string, string, Uint8Array],
    { 'ok' : UploadFileResult } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];