/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const WebLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'callerId' : UserId,
});
export const CreateDeploymentParams = IDL.Record({
  'name' : IDL.Text,
  'architecture' : IDL.Text,
  'githubUrl' : IDL.Text,
  'deployedUrl' : IDL.Text,
  'engineType' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const Deployment = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'architecture' : IDL.Text,
  'githubUrl' : IDL.Text,
  'deployedUrl' : IDL.Text,
  'callerId' : UserId,
  'engineType' : IDL.Text,
});
export const CreateIdeaParams = IDL.Record({
  'status' : IDL.Text,
  'ideaType' : IDL.Text,
  'name' : IDL.Text,
  'googleUrl' : IDL.Text,
  'instaUrl' : IDL.Text,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'deadline' : IDL.Text,
  'place' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'problem' : IDL.Text,
});
export const Idea = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'ideaType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'googleUrl' : IDL.Text,
  'instaUrl' : IDL.Text,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'deadline' : IDL.Text,
  'callerId' : UserId,
  'place' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'problem' : IDL.Text,
});
export const CreateIncubatorParams = IDL.Record({
  'name' : IDL.Text,
  'pptFileName' : IDL.Opt(IDL.Text),
  'srcFileName' : IDL.Opt(IDL.Text),
  'googleUrl' : IDL.Text,
  'instaUrl' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'docFileName' : IDL.Opt(IDL.Text),
  'youtubeUrl' : IDL.Text,
});
export const IncubatorProject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'pptFileName' : IDL.Opt(IDL.Text),
  'srcFileName' : IDL.Opt(IDL.Text),
  'googleUrl' : IDL.Text,
  'instaUrl' : IDL.Text,
  'callerId' : UserId,
  'imageUrl' : IDL.Opt(IDL.Text),
  'docFileName' : IDL.Opt(IDL.Text),
  'youtubeUrl' : IDL.Text,
});
export const CreateTaskParams = IDL.Record({
  'description' : IDL.Text,
  'taskDate' : IDL.Text,
  'taskTime' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'taskDate' : IDL.Text,
  'taskTime' : IDL.Text,
  'callerId' : UserId,
});
export const ObjectId = IDL.Text;
export const DownloadFileResult = IDL.Record({
  'contentType' : IDL.Text,
  'data' : IDL.Vec(IDL.Nat8),
  'filename' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'pendingIdeas' : IDL.Nat,
  'liveProjects' : IDL.Nat,
  'completedProjects' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
});
export const UpdateDeploymentParams = IDL.Record({
  'name' : IDL.Text,
  'architecture' : IDL.Text,
  'githubUrl' : IDL.Text,
  'deployedUrl' : IDL.Text,
  'engineType' : IDL.Text,
});
export const UpdateIdeaParams = IDL.Record({
  'status' : IDL.Text,
  'ideaType' : IDL.Text,
  'name' : IDL.Text,
  'googleUrl' : IDL.Text,
  'instaUrl' : IDL.Text,
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'deadline' : IDL.Text,
  'place' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'problem' : IDL.Text,
});
export const UpdateIncubatorParams = IDL.Record({
  'name' : IDL.Text,
  'pptFileName' : IDL.Opt(IDL.Text),
  'srcFileName' : IDL.Opt(IDL.Text),
  'googleUrl' : IDL.Text,
  'instaUrl' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'docFileName' : IDL.Opt(IDL.Text),
  'youtubeUrl' : IDL.Text,
});
export const UpdateTaskParams = IDL.Record({
  'description' : IDL.Text,
  'taskDate' : IDL.Text,
  'taskTime' : IDL.Text,
});
export const UploadFileResult = IDL.Record({
  'contentType' : IDL.Text,
  'size' : IDL.Nat,
  'filename' : IDL.Text,
  'objectId' : ObjectId,
});

export const idlService = IDL.Service({
  'addWebLink' : IDL.Func([IDL.Text, IDL.Text], [WebLink], []),
  'createDeployment' : IDL.Func([CreateDeploymentParams], [Deployment], []),
  'createIdea' : IDL.Func([CreateIdeaParams], [Idea], []),
  'createIncubatorProject' : IDL.Func(
      [CreateIncubatorParams],
      [IncubatorProject],
      [],
    ),
  'createTask' : IDL.Func([CreateTaskParams], [Task], []),
  'deleteDeployment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteFile' : IDL.Func([ObjectId], [IDL.Bool], []),
  'deleteIdea' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteIncubatorProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteWebLink' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'downloadFile' : IDL.Func(
      [ObjectId],
      [IDL.Opt(DownloadFileResult)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDeployments' : IDL.Func([], [IDL.Vec(Deployment)], ['query']),
  'getIdeas' : IDL.Func([], [IDL.Vec(Idea)], ['query']),
  'getIncubatorProjects' : IDL.Func([], [IDL.Vec(IncubatorProject)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getWebLinks' : IDL.Func([], [IDL.Vec(WebLink)], ['query']),
  'saveUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [UserProfile],
      [],
    ),
  'updateDeployment' : IDL.Func(
      [IDL.Nat, UpdateDeploymentParams],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateIdea' : IDL.Func(
      [IDL.Nat, UpdateIdeaParams],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateIncubatorProject' : IDL.Func(
      [IDL.Nat, UpdateIncubatorParams],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateTask' : IDL.Func(
      [IDL.Nat, UpdateTaskParams],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadIdeaPhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
      [],
    ),
  'uploadIncubatorDoc' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
      [],
    ),
  'uploadIncubatorImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
      [],
    ),
  'uploadIncubatorPpt' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
      [],
    ),
  'uploadIncubatorSrc' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
      [],
    ),
  'uploadProfilePhoto' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const WebLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'callerId' : UserId,
  });
  const CreateDeploymentParams = IDL.Record({
    'name' : IDL.Text,
    'architecture' : IDL.Text,
    'githubUrl' : IDL.Text,
    'deployedUrl' : IDL.Text,
    'engineType' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const Deployment = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'architecture' : IDL.Text,
    'githubUrl' : IDL.Text,
    'deployedUrl' : IDL.Text,
    'callerId' : UserId,
    'engineType' : IDL.Text,
  });
  const CreateIdeaParams = IDL.Record({
    'status' : IDL.Text,
    'ideaType' : IDL.Text,
    'name' : IDL.Text,
    'googleUrl' : IDL.Text,
    'instaUrl' : IDL.Text,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'deadline' : IDL.Text,
    'place' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'problem' : IDL.Text,
  });
  const Idea = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'ideaType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'googleUrl' : IDL.Text,
    'instaUrl' : IDL.Text,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'deadline' : IDL.Text,
    'callerId' : UserId,
    'place' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'problem' : IDL.Text,
  });
  const CreateIncubatorParams = IDL.Record({
    'name' : IDL.Text,
    'pptFileName' : IDL.Opt(IDL.Text),
    'srcFileName' : IDL.Opt(IDL.Text),
    'googleUrl' : IDL.Text,
    'instaUrl' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'docFileName' : IDL.Opt(IDL.Text),
    'youtubeUrl' : IDL.Text,
  });
  const IncubatorProject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'pptFileName' : IDL.Opt(IDL.Text),
    'srcFileName' : IDL.Opt(IDL.Text),
    'googleUrl' : IDL.Text,
    'instaUrl' : IDL.Text,
    'callerId' : UserId,
    'imageUrl' : IDL.Opt(IDL.Text),
    'docFileName' : IDL.Opt(IDL.Text),
    'youtubeUrl' : IDL.Text,
  });
  const CreateTaskParams = IDL.Record({
    'description' : IDL.Text,
    'taskDate' : IDL.Text,
    'taskTime' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'taskDate' : IDL.Text,
    'taskTime' : IDL.Text,
    'callerId' : UserId,
  });
  const ObjectId = IDL.Text;
  const DownloadFileResult = IDL.Record({
    'contentType' : IDL.Text,
    'data' : IDL.Vec(IDL.Nat8),
    'filename' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'pendingIdeas' : IDL.Nat,
    'liveProjects' : IDL.Nat,
    'completedProjects' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
  });
  const UpdateDeploymentParams = IDL.Record({
    'name' : IDL.Text,
    'architecture' : IDL.Text,
    'githubUrl' : IDL.Text,
    'deployedUrl' : IDL.Text,
    'engineType' : IDL.Text,
  });
  const UpdateIdeaParams = IDL.Record({
    'status' : IDL.Text,
    'ideaType' : IDL.Text,
    'name' : IDL.Text,
    'googleUrl' : IDL.Text,
    'instaUrl' : IDL.Text,
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'deadline' : IDL.Text,
    'place' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'problem' : IDL.Text,
  });
  const UpdateIncubatorParams = IDL.Record({
    'name' : IDL.Text,
    'pptFileName' : IDL.Opt(IDL.Text),
    'srcFileName' : IDL.Opt(IDL.Text),
    'googleUrl' : IDL.Text,
    'instaUrl' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'docFileName' : IDL.Opt(IDL.Text),
    'youtubeUrl' : IDL.Text,
  });
  const UpdateTaskParams = IDL.Record({
    'description' : IDL.Text,
    'taskDate' : IDL.Text,
    'taskTime' : IDL.Text,
  });
  const UploadFileResult = IDL.Record({
    'contentType' : IDL.Text,
    'size' : IDL.Nat,
    'filename' : IDL.Text,
    'objectId' : ObjectId,
  });
  
  return IDL.Service({
    'addWebLink' : IDL.Func([IDL.Text, IDL.Text], [WebLink], []),
    'createDeployment' : IDL.Func([CreateDeploymentParams], [Deployment], []),
    'createIdea' : IDL.Func([CreateIdeaParams], [Idea], []),
    'createIncubatorProject' : IDL.Func(
        [CreateIncubatorParams],
        [IncubatorProject],
        [],
      ),
    'createTask' : IDL.Func([CreateTaskParams], [Task], []),
    'deleteDeployment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteFile' : IDL.Func([ObjectId], [IDL.Bool], []),
    'deleteIdea' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteIncubatorProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteWebLink' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'downloadFile' : IDL.Func(
        [ObjectId],
        [IDL.Opt(DownloadFileResult)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDeployments' : IDL.Func([], [IDL.Vec(Deployment)], ['query']),
    'getIdeas' : IDL.Func([], [IDL.Vec(Idea)], ['query']),
    'getIncubatorProjects' : IDL.Func(
        [],
        [IDL.Vec(IncubatorProject)],
        ['query'],
      ),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getWebLinks' : IDL.Func([], [IDL.Vec(WebLink)], ['query']),
    'saveUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [UserProfile],
        [],
      ),
    'updateDeployment' : IDL.Func(
        [IDL.Nat, UpdateDeploymentParams],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateIdea' : IDL.Func(
        [IDL.Nat, UpdateIdeaParams],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateIncubatorProject' : IDL.Func(
        [IDL.Nat, UpdateIncubatorParams],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateTask' : IDL.Func(
        [IDL.Nat, UpdateTaskParams],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadIdeaPhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
        [],
      ),
    'uploadIncubatorDoc' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
        [],
      ),
    'uploadIncubatorImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
        [],
      ),
    'uploadIncubatorPpt' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
        [],
      ),
    'uploadIncubatorSrc' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
        [],
      ),
    'uploadProfilePhoto' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [IDL.Variant({ 'ok' : UploadFileResult, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };