/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Deployment {
    id: bigint;
    name: string;
    createdAt: Timestamp;
    architecture: string;
    githubUrl: string;
    deployedUrl: string;
    callerId: UserId;
    engineType: string;
}
export interface CreateIdeaParams {
    status: string;
    ideaType: string;
    name: string;
    googleUrl: string;
    instaUrl: string;
    description: string;
    photoUrl?: string;
    deadline: string;
    place: string;
    youtubeUrl: string;
    problem: string;
}
export interface UpdateTaskParams {
    description: string;
    taskDate: string;
    taskTime: string;
}
export interface Task {
    id: bigint;
    createdAt: Timestamp;
    description: string;
    taskDate: string;
    taskTime: string;
    callerId: UserId;
}
export interface WebLink {
    id: bigint;
    url: string;
    title: string;
    callerId: UserId;
}
export interface IncubatorProject {
    id: bigint;
    name: string;
    createdAt: Timestamp;
    pptFileName?: string;
    srcFileName?: string;
    googleUrl: string;
    instaUrl: string;
    callerId: UserId;
    imageUrl?: string;
    docFileName?: string;
    youtubeUrl: string;
}
export interface Idea {
    id: bigint;
    status: string;
    ideaType: string;
    name: string;
    createdAt: Timestamp;
    googleUrl: string;
    instaUrl: string;
    description: string;
    photoUrl?: string;
    deadline: string;
    callerId: UserId;
    place: string;
    youtubeUrl: string;
    problem: string;
}
export interface CreateTaskParams {
    description: string;
    taskDate: string;
    taskTime: string;
}
export interface UpdateIdeaParams {
    status: string;
    ideaType: string;
    name: string;
    googleUrl: string;
    instaUrl: string;
    description: string;
    photoUrl?: string;
    deadline: string;
    place: string;
    youtubeUrl: string;
    problem: string;
}
export interface DashboardStats {
    pendingIdeas: bigint;
    liveProjects: bigint;
    completedProjects: bigint;
}
export interface CreateIncubatorParams {
    name: string;
    pptFileName?: string;
    srcFileName?: string;
    googleUrl: string;
    instaUrl: string;
    imageUrl?: string;
    docFileName?: string;
    youtubeUrl: string;
}
export type UserId = Principal;
export interface UpdateDeploymentParams {
    name: string;
    architecture: string;
    githubUrl: string;
    deployedUrl: string;
    engineType: string;
}
export interface UpdateIncubatorParams {
    name: string;
    pptFileName?: string;
    srcFileName?: string;
    googleUrl: string;
    instaUrl: string;
    imageUrl?: string;
    docFileName?: string;
    youtubeUrl: string;
}
export interface CreateDeploymentParams {
    name: string;
    architecture: string;
    githubUrl: string;
    deployedUrl: string;
    engineType: string;
}
export interface UserProfile {
    principal: UserId;
    displayName: string;
    email: string;
    profilePhotoUrl?: string;
}
export interface backendInterface {
    addWebLink(title: string, url: string): Promise<WebLink>;
    createDeployment(params: CreateDeploymentParams): Promise<Deployment>;
    createIdea(params: CreateIdeaParams): Promise<Idea>;
    createIncubatorProject(params: CreateIncubatorParams): Promise<IncubatorProject>;
    createTask(params: CreateTaskParams): Promise<Task>;
    deleteDeployment(id: bigint): Promise<boolean>;
    deleteIdea(id: bigint): Promise<boolean>;
    deleteIncubatorProject(id: bigint): Promise<boolean>;
    deleteTask(id: bigint): Promise<boolean>;
    deleteWebLink(id: bigint): Promise<boolean>;
    getDashboardStats(): Promise<DashboardStats>;
    getDeployments(): Promise<Array<Deployment>>;
    getIdeas(): Promise<Array<Idea>>;
    getIncubatorProjects(): Promise<Array<IncubatorProject>>;
    getTasks(): Promise<Array<Task>>;
    getUserProfile(): Promise<UserProfile | null>;
    getWebLinks(): Promise<Array<WebLink>>;
    saveUserProfile(displayName: string, email: string, profilePhotoUrl: string | null): Promise<UserProfile>;
    updateDeployment(id: bigint, params: UpdateDeploymentParams): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateIdea(id: bigint, params: UpdateIdeaParams): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateIncubatorProject(id: bigint, params: UpdateIncubatorParams): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateTask(id: bigint, params: UpdateTaskParams): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CreateIdeaParams as _CreateIdeaParams, CreateIncubatorParams as _CreateIncubatorParams, Idea as _Idea, IncubatorProject as _IncubatorProject, Timestamp as _Timestamp, UpdateIdeaParams as _UpdateIdeaParams, UpdateIncubatorParams as _UpdateIncubatorParams, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addWebLink(arg0: string, arg1: string): Promise<WebLink> {
        if (this.processError) {
            try {
                const result = await this.actor.addWebLink(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWebLink(arg0, arg1);
            return result;
        }
    }
    async createDeployment(arg0: CreateDeploymentParams): Promise<Deployment> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeployment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeployment(arg0);
            return result;
        }
    }
    async createIdea(arg0: CreateIdeaParams): Promise<Idea> {
        if (this.processError) {
            try {
                const result = await this.actor.createIdea(to_candid_CreateIdeaParams_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Idea_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIdea(to_candid_CreateIdeaParams_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Idea_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createIncubatorProject(arg0: CreateIncubatorParams): Promise<IncubatorProject> {
        if (this.processError) {
            try {
                const result = await this.actor.createIncubatorProject(to_candid_CreateIncubatorParams_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_IncubatorProject_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIncubatorProject(to_candid_CreateIncubatorParams_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_IncubatorProject_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTask(arg0: CreateTaskParams): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0);
            return result;
        }
    }
    async deleteDeployment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeployment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeployment(arg0);
            return result;
        }
    }
    async deleteIdea(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIdea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIdea(arg0);
            return result;
        }
    }
    async deleteIncubatorProject(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncubatorProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncubatorProject(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteWebLink(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWebLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWebLink(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDeployments(): Promise<Array<Deployment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeployments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeployments();
            return result;
        }
    }
    async getIdeas(): Promise<Array<Idea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIdeas();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIdeas();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncubatorProjects(): Promise<Array<IncubatorProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncubatorProjects();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncubatorProjects();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebLinks(): Promise<Array<WebLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebLinks();
            return result;
        }
    }
    async saveUserProfile(arg0: string, arg1: string, arg2: string | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
                return from_candid_UserProfile_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
            return from_candid_UserProfile_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDeployment(arg0: bigint, arg1: UpdateDeploymentParams): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeployment(arg0, arg1);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeployment(arg0, arg1);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateIdea(arg0: bigint, arg1: UpdateIdeaParams): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIdea(arg0, to_candid_UpdateIdeaParams_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIdea(arg0, to_candid_UpdateIdeaParams_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateIncubatorProject(arg0: bigint, arg1: UpdateIncubatorParams): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncubatorProject(arg0, to_candid_UpdateIncubatorParams_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncubatorProject(arg0, to_candid_UpdateIncubatorParams_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTask(arg0: bigint, arg1: UpdateTaskParams): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1);
                return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1);
            return from_candid_variant_n16(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Idea_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Idea): Idea {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_IncubatorProject_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncubatorProject): IncubatorProject {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    displayName: string;
    email: string;
    profilePhotoUrl: [] | [string];
}): {
    principal: UserId;
    displayName: string;
    email: string;
    profilePhotoUrl?: string;
} {
    return {
        principal: value.principal,
        displayName: value.displayName,
        email: value.email,
        profilePhotoUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.profilePhotoUrl))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    ideaType: string;
    name: string;
    createdAt: _Timestamp;
    googleUrl: string;
    instaUrl: string;
    description: string;
    photoUrl: [] | [string];
    deadline: string;
    callerId: _UserId;
    place: string;
    youtubeUrl: string;
    problem: string;
}): {
    id: bigint;
    status: string;
    ideaType: string;
    name: string;
    createdAt: Timestamp;
    googleUrl: string;
    instaUrl: string;
    description: string;
    photoUrl?: string;
    deadline: string;
    callerId: UserId;
    place: string;
    youtubeUrl: string;
    problem: string;
} {
    return {
        id: value.id,
        status: value.status,
        ideaType: value.ideaType,
        name: value.name,
        createdAt: value.createdAt,
        googleUrl: value.googleUrl,
        instaUrl: value.instaUrl,
        description: value.description,
        photoUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.photoUrl)),
        deadline: value.deadline,
        callerId: value.callerId,
        place: value.place,
        youtubeUrl: value.youtubeUrl,
        problem: value.problem
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    createdAt: _Timestamp;
    pptFileName: [] | [string];
    srcFileName: [] | [string];
    googleUrl: string;
    instaUrl: string;
    callerId: _UserId;
    imageUrl: [] | [string];
    docFileName: [] | [string];
    youtubeUrl: string;
}): {
    id: bigint;
    name: string;
    createdAt: Timestamp;
    pptFileName?: string;
    srcFileName?: string;
    googleUrl: string;
    instaUrl: string;
    callerId: UserId;
    imageUrl?: string;
    docFileName?: string;
    youtubeUrl: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        pptFileName: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.pptFileName)),
        srcFileName: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.srcFileName)),
        googleUrl: value.googleUrl,
        instaUrl: value.instaUrl,
        callerId: value.callerId,
        imageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.imageUrl)),
        docFileName: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.docFileName)),
        youtubeUrl: value.youtubeUrl
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Idea>): Array<Idea> {
    return value.map((x)=>from_candid_Idea_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncubatorProject>): Array<IncubatorProject> {
    return value.map((x)=>from_candid_IncubatorProject_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CreateIdeaParams_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateIdeaParams): _CreateIdeaParams {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateIncubatorParams_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateIncubatorParams): _CreateIncubatorParams {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateIdeaParams_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateIdeaParams): _UpdateIdeaParams {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateIncubatorParams_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateIncubatorParams): _UpdateIncubatorParams {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    ideaType: string;
    name: string;
    googleUrl: string;
    instaUrl: string;
    description: string;
    photoUrl?: string;
    deadline: string;
    place: string;
    youtubeUrl: string;
    problem: string;
}): {
    status: string;
    ideaType: string;
    name: string;
    googleUrl: string;
    instaUrl: string;
    description: string;
    photoUrl: [] | [string];
    deadline: string;
    place: string;
    youtubeUrl: string;
    problem: string;
} {
    return {
        status: value.status,
        ideaType: value.ideaType,
        name: value.name,
        googleUrl: value.googleUrl,
        instaUrl: value.instaUrl,
        description: value.description,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        deadline: value.deadline,
        place: value.place,
        youtubeUrl: value.youtubeUrl,
        problem: value.problem
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    pptFileName?: string;
    srcFileName?: string;
    googleUrl: string;
    instaUrl: string;
    imageUrl?: string;
    docFileName?: string;
    youtubeUrl: string;
}): {
    name: string;
    pptFileName: [] | [string];
    srcFileName: [] | [string];
    googleUrl: string;
    instaUrl: string;
    imageUrl: [] | [string];
    docFileName: [] | [string];
    youtubeUrl: string;
} {
    return {
        name: value.name,
        pptFileName: value.pptFileName ? candid_some(value.pptFileName) : candid_none(),
        srcFileName: value.srcFileName ? candid_some(value.srcFileName) : candid_none(),
        googleUrl: value.googleUrl,
        instaUrl: value.instaUrl,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        docFileName: value.docFileName ? candid_some(value.docFileName) : candid_none(),
        youtubeUrl: value.youtubeUrl
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
